#!/usr/bin/env python3
"""Rebuild the corpus manifest from the YAML front-matter of every content/**/*.md.
Run from the repo/ directory:  python3 scripts/build-manifest.py

Emits two artifacts from one source:
  - manifest.json            machine-readable index (for tooling / future sessions)
  - ch-sims/data/manifest.js window.WB_MANIFEST global (for the portal)

The .js wrapper exists so index.html can read the corpus even when opened from
file:// locally, where browsers block fetch() of a sibling .json (CORS). This mirrors
the existing data/canon.js pattern. See memory: portal-rendering-decision.
"""
import os, json

ROOT = "content"
JS_OUT = os.path.join("ch-sims", "data", "manifest.js")
WORLD_ORDER = ["cognitive-husbandry", "new-tripoli", "alt-history"]
WORLD_LABEL = {
    "cognitive-husbandry": "Cognitive Husbandry",
    "new-tripoli": "New Tripoli",
    "alt-history": "Alt-History Sims",
}


def parse_front_matter(path):
    txt = open(path, encoding="utf-8").read()
    if not txt.lstrip().startswith("---"):
        return None
    _, fm, body = txt.split("---", 2)
    d = {}
    for line in fm.strip().splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        k, v = k.strip(), v.strip()
        if v.startswith("[") and v.endswith("]"):
            v = [x.strip() for x in v[1:-1].split(",") if x.strip()]
        else:
            v = v.strip('"')
        d[k] = v
    d["words"] = len(body.split())
    d["bytes"] = os.path.getsize(path)
    d["path"] = path.replace("\\", "/")
    return d


def main():
    entries = []
    for dp, _, fns in os.walk(ROOT):
        for f in sorted(fns):
            if f.endswith(".md"):
                e = parse_front_matter(os.path.join(dp, f))
                if e:
                    entries.append(e)

    def key(e):
        w = e.get("world", "zz")
        return (WORLD_ORDER.index(w) if w in WORLD_ORDER else 99,
                e.get("type", ""), e["path"])

    entries.sort(key=key)
    worlds = sorted({e["world"] for e in entries},
                    key=lambda w: WORLD_ORDER.index(w) if w in WORLD_ORDER else 99)
    manifest = {
        "name": "World Building",
        "description": "Creative alt-history & speculative-world scenarios. "
                       "Source-of-truth corpus for the portal/community build-out.",
        "count": len(entries),
        "worlds": worlds,
        "worldLabels": {w: WORLD_LABEL.get(w, w.replace("-", " ").title()) for w in worlds},
        "documents": entries,
    }
    with open("manifest.json", "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2, ensure_ascii=False)

    # JS wrapper for the portal (file://-safe; mirrors data/canon.js)
    os.makedirs(os.path.dirname(JS_OUT), exist_ok=True)
    with open(JS_OUT, "w", encoding="utf-8") as fh:
        fh.write("/* AUTO-GENERATED by scripts/build-manifest.py — do not edit by hand. */\n")
        fh.write("window.WB_MANIFEST = ")
        json.dump(manifest, fh, indent=2, ensure_ascii=False)
        fh.write(";\n")

    print(f"manifest.json + {JS_OUT}: {len(entries)} docs across {len(worlds)} worlds")


if __name__ == "__main__":
    main()
